### PR TITLE
Proposal: Check user role in a more readable way

### PR DESCRIPTION
**Pull request by oliverds**
Instead of `$user->id_role == Model_Role::ROLE_ADMIN` do `$user->is_admin()`.

I think is cleaner and more readable.

* `$user->id_role == Model_Role::ROLE_ADMIN` => `$user->is_admin()`
* `$user->id_role == Model_Role::ROLE_MODERATOR` => `$user->is_moderator()`
* `$user->id_role == Model_Role::ROLE_TRANSLATOR` => `$user->is_translator()`

### CODE REVIEW

**Comment by neo22s** [comment]
I think is great change, now we need to remember to use this xD @kotsios5 ok? hehe

Maybe we can add also a function is_role(Model_Role::ROLE_WHATEVER) so in case we have a custom theme we can use this function ;)

**Comment by kotsios5** [comment]
Yes, looks better now!

**Comment by oliverds** [comment]
> Maybe we can add also a function is_role(Model_Role::ROLE_WHATEVER) so in case we have a custom theme we can use this function ;)

@neo22s Did you mean in the case of custom user roles no?

**Comment by neo22s** [comment]
yes! in case we have custom user roles for a theme or something like that xD but no need to put it now...we will just add a "if" and ready...

**Pull request merged**
