### PR TITLE
Fix for: Fatal error: Can't use function return value in write context in /oc/common/classes/controller/panel/user.php

### PR DESCRIPTION
**Pull request by AndreasRicci**
Fix for: Fatal error: Can't use function return value in write context in /oc/common/classes/controller/panel/user.php

### CODE REVIEW

**Comment by oliverds** [comment]
It's a limitation of empty() in PHP versions below 5.5.

OC 2.5.0 requires minimum PHP 5.5.

**Comment by AndreasRicci** [comment]
I know. I am on 5.6.
screen shot 2015-08-20 at 12 36 48 pm

**Comment by oliverds** [comment]
Then is a bit strange you shouldn't have that error.

What version shows at /oc-panel/tools/phpinfo?

**Comment by AndreasRicci** [comment]
Aha! Interesting. Seems this is an issue with my webhost and not openclassifieds :).
Thanks. 

PHP Version 5.4.43

**Pull request closed without merging**
